// ==UserScript==
// @name           FaceBook
// @namespace      *
// @description    Facebook Fuck Yeah
// @include        *
// ==/UserScript==

// Read the page
readPage = document.body.innerHTML;


// Find strings that match FaceBook image fiels
postfixRegex = /\d+\_\d+\_\d+\_(a|n|q|s)\.jpg/gi;
/*postfixRegex = /\d+\_\d+\_\d+\_(a|n|q|s)\.jpg/gi;*/

foundMatch = readPage.match(postfixRegex);

if(foundMatch)
  var matches = foundMatch.length;
   for (i=0;i<matches;i++)
     {
       var profileID = foundMatch[i].split("_")[0];
       var profileImage = "http://graph.facebook.com/"+profileID+"/picture?type=small";	// TO DO(3)
       var profileLink = "https://www.facebook.com/profile.php?id="+profileID;
       var linkIcon = '<a href="'+profileLink+'" /><img src="'+profileImage+'" style="float:left;"/></a>'; 
       createFBDiv(linkIcon)      
      }


function createFBDiv(linkIcon){
  var divTag = document.createElement("div");
   divTag.id = "fkd5d3gkeh4trelsn76iv"; // Generated by feline fuzzer
   divTag.style.margin = "0px auto";
   divTag.style.position = "relative";
   divTag.style.border = "2px solid #2266AA";
   divTag.style.width = "100%";
   divTag.className ="FBDiv";
   divTag.innerHTML += linkIcon;
   document.body.appendChild(divTag);
 }

/*****************************************************************
TO DO
 - Check location of foundMatch
  i. if !text

 - Add more regexes
  i. Image File Naming Schemes
    1. 33928_152487554786401_100000754713948_237838_7543147_n.jpg
       UNKNOWN_UNKNOWN_$profileID_UNKNOWN_UNKNOWN_n.jpg
    2. 173272_100001840133300_6350707_n.jpg
       UNKNOWN_$profileID_UNKNOWN_n.jpg
    3. n40700018_31257967_7692.jpg 
       n$profileID_UNKNOWN_UNKNOWN.jpg

 - Check if not a profile profileImage =
  i. http://static.ak.fbcdn.net/rsrc.php/v1/yh/r/C5yt7Cqf3zU.jpg
    1. then not a profile
    
RESOURCES
 - http://stackoverflow.com/questions/1444409/in-javascript-how-can-i-replace-text-in-an-html-page-without-affecting-the-tags
******************************************************************/
